apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
  namespace: personal-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      hostNetwork: true
      containers:
        - name: ddns
          image: favonia/cloudflare-ddns:latest
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          env:
            - name: CLOUDFLARE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: personal-infra-secrets
                  key: CLOUDFLARE_API_TOKEN
            - name: DOMAINS
              value: "arthos.dev.br,flix.arthos.dev.br,search.arthos.dev.br,searchnode.arthos.dev.br,priscilacatarino.com.br"
            - name: PROXIED
              value: "true"
            - name: IP4_PROVIDER
              value: "none"
