apiVersion: apps/v1
kind: Deployment
metadata:
  name: priscilacatarinopsi
  namespace: personal-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: priscilacatarinopsi
  template:
    metadata:
      labels:
        app: priscilacatarinopsi
    spec:
      imagePullSecrets:
        - name: ghcr-login-secret-priscila
      containers:
        - name: web
          image: ghcr.io/pitykohwalter/priscilacatarinocom:latest
          ports:
            - containerPort: 80
          env:
            - name: UID
              value: "1000"
            - name: GID
              value: "100"
            - name: GIDLIST
              value: "100"
---
apiVersion: v1
kind: Service
metadata:
  name: priscilacatarinopsi-svc
  namespace: personal-infra
spec:
  selector:
    app: priscilacatarinopsi
  ports:
    - port: 80
      targetPort: 80
